# -*- coding: utf-8 -*-
from __future__ import division

inv= int(input('digite o valor do investimento:'))
tx= input ('digite o valor da taxa anual:')

inv1=inv+(tx*inv)
print (inv1)
inv2=inv1+(tx*inv1)
print (inv2)
inv3=inv2+(tx*inv2)
print (inv3)
inv4=inv3+(tx*inv3)
print (inv4)
inv5=inv4+(tx*inv4)
print (inv5)
inv6=inv5+(tx*inv5)
print (inv6)
inv7=inv6+(tx*inv6)
print (inv7)
inv8=inv7+(tx*inv7)
print(inv8)
inv9=inv8+(tx*inv8)
print (inv9)
inv10=inv9+(tx*inv9)
print (inv10)