t1=int(input('Digite o número de tomadas da régua 1:'))
t2=int(input('Digite o número de tomadas da régua 2:'))
t3=int(input('Digite o número de tomadas da régua 3:'))
t4=int(input('Digite o número de tomadas da régua 4:'))
a=(t1-1)+(t2-1)+(t3-1)+(t4)
print('O número total de tomadas é %d' %a)
