# -*- coding: utf-8 -*-
#COMECE AQUI ABAIXO
print('vamos calcular sua media')
print('\n')
nota1 = float(input('digite sua primeira nota; '))
print('\n')
nota2 = float(input('ditite sua segunda nota; '))
print('\n')
nota3 = float(input('digite sua terceira nota; '))
print('\n')
nota4 = float(input('digite sua quarta nota;'))
media  = ((nota1+nota2+nota3+nota4)/4)
print('\n')
print(input('sua media final é: %.2f ' %media))
print('\n')
print('vamos calcular a sua em centímetros!')
print('\n')
altu1 = float(input('digite sua altura em metros, com até duas casas decimais; '))
cent2 = (altu1*100)
print(input('sua altura é ; %.2d ' %cent2))
print('\n')
print('gostaría de saber se você possui o peso ideal?')
print('\n')
altura = float(input('digite a sua altura em metros ,com até duas casas decimais ; '))
pesoideal = ((72.7*altura)-58)
print(input('seu peso ideal é de ; %.2f' %pesoideal))
print('\n')
print('gostaria de saber a área do círculo, eu posso lhe ajudar')
print('\n')
raio = float(input('digite o raio do cículo'))
area =(3.16*(raio**2))
print(input('a área do círculo de raio citado é de ; %.2f' %area)