print('seja bem vindo ao programa, mãe')
print('-------------------------------------\n')
nome=str(input('Qual seu nome?'))
print('Olá '+nome+'. Farei algumas perguntas')
idade=int(input('Qual sua idade ?'))
print(' Ok, obrigada Creusa')