a = input(' ')
if type(a)==type(2):
    b=int(a//(10**7))
    restob = int(a%(10**7))
    c=int(restob//(10**6))
    restoc=int(restob%(10**6))
    d=int(restoc//(10**5))
    restod=(restoc%(10**5))
    e=int(restod//(10**4))
    restoe=int(restod%(10**4))
    f=int(restoe//(10**3))
    restof=int(restoe%(10**3))
    g=int(restof//(10**2))
    restog=(restof%(10**2))
    h=int(restog//10)
    i=int(restog%10)
    print(b+c+d+e+f+g+h+i)
else:
    print('NAO SEI')