n=int(input('digite um número de 4 dígitos:'))
a=int(input('digite o primeiro algarismo do seu número:'))
b=int(input('digite o segundo algarismo do seu número:'))
c=int(input('digite o terceiro algarismo do seu número:'))
d=int(input('digite o quarto algarismo do seu número:'))
str(a)
n1=(a+b)
n2=(a,c)
n3=(a,d)
n4=(b,a)
n5=(b,c)
n6=(b,d)
n7=(c,a)
n8=(c,b)
n9=(c,d)
n10=(d,a)
n11=(d,b)
n12=(d,c)
print(n1)
