# -*- coding: utf-8 -*-
from __future__ import division

#COMECE SEU CODIGO AQUI
i= float(input('Digite o valor do investimento inicial:'))
t= float(input('Digite o valor da taxa de crescimento percentual:'))
a= i+(i*t)
b= a+(a*t)
c= b+(b*t)
d= c+(c*t)
e= d+(d*t)
f= e+(e*t)
g= f+(f*t)
h= g+(g*t)
j= h+(h*t)
k= j+(j*t)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(j)
print(k)