# -*- coding: utf-8 -*-
#COMECE AQUI ABAIXO
print('Olá, seja bem vindo ao Manu Cálculos!')
print('-------------------------------------\n')
nome= str(input('Qual o seu nome?'))
print('E aê \n '+nome+'. Preciso que informe suas 4 notas bimestrais abaixo para que eu possa calcular a sua média\n')
Nota1= float(input('insira a nota 1'))
Nota2= float(input('insira a nota 2'))
Nota3= float(input('insira a nota 3'))
Nota4= float(input('insira a nota 4'))
Média= print((Nota1+Nota2+Nota3+Nota4)/4)
if(Media>=7)
print('Parabens')
print('Espero que tenha se saído bem')
print('Até a próxima')
print('-------------------------------------\n')