idade = float(input("Qual a sua idade?: "))
altura = float(input("Qual sua altura?: "))
print('\nidade = %.2f' % idade)
print('\naltura = %.2f' % idade )
print('\nSua idade inteira é %d, sua idade nâo-inteira é %.2f e sua altura é %.2f' % (idade, idade, altura))