# -*- coding: utf-8 -*-
from __future__ import division

Capital=input('Digite o valor do capital/:')
Taxa=input('Digite o valor da taxa de crescimento:')
Saldo1=Capital+(Capital*Taxa)
Saldo2=Saldo1+(Saldo1*Taxa)
Saldo3=Saldo2+(Saldo2*Taxa)
Saldo4=Saldo3+(Saldo3*Taxa)
Saldo5=Saldo4+(Saldo4*Taxa)
Saldo6=Saldo5+(Saldo5*Taxa)
Saldo7=Saldo6+(Saldo6*Taxa)
Saldo8=Saldo7+(Saldo7*Taxa)
Saldo9=Saldo8+(Saldo8*Taxa)
Saldo10=Saldo9+(Saldo9*Taxa)
print('%.2f' %Saldo1)
print('%.2f' %Saldo2)
print('%.2f' %Saldo3)
print('%.2f' %Saldo4)
print('%.2f' %Saldo5)
print('%.2f' %Saldo6)
print('%.2f' %Saldo7)
print('%.2f' %Saldo8)
print('%.2f' %Saldo9)
print('%.2f' %Saldo10)