# -*- coding: utf-8 -*-
from __future__ import division

#COMECE SEU CODIGO AQUI
b = float(input('digite o valor do investimento: '))
a = float(input('digite o valos da taxa: '))
ano1=b+(b*a)
ano2=ano1+(ano1*a)
ano3=ano2+(ano2*a)
ano4=ano3+(ano3*a)
ano5=ano4+(ano4*a)
ano6=ano5+(ano5*a)
ano7=ano6+(ano6*a)
ano8=ano7+(ano7*a)
ano9=ano8+(ano8*a)
ano10=ano9+(ano9*a)
print('%.2f' %ano1)
print('%.2f' %ano2)
print('%.2f' %ano3)
print('%.2f' %ano4)
print('%.2f' %ano5)
print('%.2f' %ano6)
print('%.2f' %ano7)
print('%.2f' %ano8)
print('%.2f' %ano9)
print('%.2f' %ano10)
