# -*- coding: utf-8 -*-
print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))print (par(2))
print (par(5))
print (par(10))