# -*- coding: utf-8 -*-
print('Digite tres números')
p=float(input('1° número:'))
print(p)
i=float(input('2° número:'))
print(i)
n=float(input('3° número:'))
print(n)
v=float(v=p*{[((1+i)**n)-1]/i})
print(v)