# -*- coding: utf-8 -*-
from __future__ import division

a=input('informe o valor do investimento inicial a:')
b=input('informe o valor da taxa de crescimento percentual b:')
c=b/100
a1=a+(c*a)
print(a1)
a2=a+(c*a1)
print(a2)
a3=a+(c*a2)
print(a3)
a4=a+(c*a3)
print(a4)
a5=a+(c*a4)
print(a5)
a6=a+(c*a5)
print(a6)
a7=a+(c*a6)
print(a7)
a8=a+(c*a7)
print(a8)
a9=a+(c*a8)
print(a9)
a10=a+(c*a9)
print(a10)
