# -*- coding: utf-8 -*-
#COMECE AQUI ABAIXO
print('Seja bem vindo ao programa')
print('Questão 1, calcule a média de 4 notas aleatórias.')
nota1=float(input('Sua primeira nota (f):'))
print(nota1)
nota2=float(input('Sua segunda nota (f):'))
print(nota2)
nota3=float(input('Sua terceira nota (f):'))
print(nota3)
nota4=float(input('Sua quarta nota (f):'))
print(nota4)
média=(nota1+nota2+nota3+nota4)/4
print('média')
print(média)
print('---------------------------------------')
print('Questão 2, tranforme um numero de metros para centímetros')
metros=float(input('Digite uma medida em metros (f):'))
print(metros)
conversão=(metros*100)
print('conversão para centimetros')
print(conversão)
print('-----------------------------------------')
print('Questão 3, calcule o peso ideal de um corpo')
altura=float(input('Qual sua altura? (f):'))
print(altura)
pesoideal=((72.7*altura)-58)
print('Seu peso ideal é:')
print(pesoideal)
print('----------------------------------------')
print('Questão 4, calcule a área de um circulo a partir do raio')
raio=float(input('Qual o raio do círculo em metros? (f):'))
print(raio)
area=((raio*raio)*3.14)
print('Sua área é em (mxm):')
print(area)

