print(' vamos começa')
nome = str(input( ' diga seu nome ' ))
print( 'olar tudo bem' )
idade = int(input( ' digite sua idade'))
print('muito bem amigo')
altura = float(input( ' digite sua altura'))
print('%f' % altura)
print( ' tchau ')
