# -*- coding: utf-8 -*-
from __future__ import division
investimento=float(input('digite o valor inicial do investimento:'))
taxa =float(input('digite o valor da taxa de investimento:'))
i1=investimento+(taxa*investimento)
i2=i1+(taxa*i1)
i3=i2+(taxa*i2)
i4=i3+(taxa*i3)
i5=i4+(taxa*i4)
i6=i5+(taxa*i5)
i7=i6+(taxa*i6)
i8=i7+(taxa*i7)
i9=i8+(taxa*i8)
i10=i9+(taxa*i9)
print('%.2f'%i1)
print('%.2f'%i2)
print('%.2f'%i3)
print('%.2f'%i4)
print('%.2f'%i5)
print('%.2f'%i6)
print('%.2f'%i7)
print('%.2f'%i8)
print('%.2f'%i9)
print('%.2f'%i10)