# -*- coding: utf-8 -*-
#COMECE AQUI ABAIXO
print("Klinsmann Berra Rabelo")
print("18")
print(11+1037)
print((9*35+160)/5)
print(3.14159*5*5*30)
print((2+5)*(2+5))
idade=int(input("sua idade (i): "))
print(idade)
idade=float(input("sua idade (f): "))
print(idade)
idade=float(input("sua idade (f): "))
print("a idade do individuo é %d" % idade)
print("a idade do individuo é %.2f" % idade)
print("idade é %d" % idade)