# -*- coding: utf-8 -*-
CV=INT(INPUT('DIGITE O TOTAL DE VITÓRIAS DO CORMENGO:'))
CE=INT(INPUT('DIGITE O TOTAL DE EMPATES DO CORMENGO:'))
CS=INT(INPUT('DIGITE O SALDO DE GOLS DO CORMENGO:'))
FV=INT(INPUT('DIGITE O TOTAL DE VITÓRIAS DO FLAMINTHIAS:'))
FE=INT(INPUT('DIGITE O TOTAL DE EMPATES DO FLAMINTHIAS:'))
FS=INT(INPUT('DIGITE O SALDO DE GOLS DO FLAMINTHIAS:'))
PC=(CV*3)+CE
PF=(FV*3)+FE
if PC>PF:
    PRINT('C)
elif PF>PC:
    PRINT('F')
else:
    if CS>FS:
        PRINT('C)
    elif FS>CS:
        PRINT('F')
    else:
        print('=')



