n=int(input('digite um número de 4 dígitos:'))
a=int(input('digite o primeiro algarismo do seu número:'))
b=int(input('digite o segundo algarismo do seu número:'))
c=int(input('digite o terceiro algarismo do seu número:'))
d=int(input('digite o quarto algarismo do seu número:'))
n1=str(a)+str(b)
n2=str(a)+str(c)
n3=str(a)+str(d)
n4=str(b)+str(a)
n5=str(b)+str(c)
n6=str(b)+str(d)
n7=str(c)+str(a)
n8=str(c)+str(b)
n9=str(c)+str(d)
n10=str(d)+str(a)
n11=str(d)+str(b)
n12=str(c)+str(d)
if (n1*n9)==n or (n2*n6)==n or (n3*n5)==n or (n1*n12)==n or (n2*n11)==n or (n3*n8)==n or (n4*n9)==n or (n4*n12)==n or (n5*n10)==n or (n6*n7)==n or (n7*n11)==n or (n8*n10)==n :
    print('é um número vampiro')
else:
    print('não é um número vampiro')