# -*- coding: utf-8 -*-
from __future__ import division

#COMECE SEU CODIGO AQUI
a = input ('digite o valor do investimento:')
b = input ('digite o valor da taxa de investimento:')
c = a+(a*b)
d = c+(c*b)
e = d+(d*b)
f = e+(e*b)
g = f+(f*b)
h = g+(g*b)
i = h+(h*b)
j = i+(i*b)
k = j+(j*b)
l = k+(k*b)
print ('%.2f'%c)
print ('%.2f'%d)
print ('%.2f'%e)
print ('%.2f'%f)
print ('%.2f'%g)
print ('%.2f'%h)
print ('%.2f'%i)
print ('%.2f'%j)
print ('%.2f'%k)
print ('%.2f'%l)