# -*- coding: utf-8 -*-
a1=int(input('digite numero apostado a1:')
a2=int(input('digite numero apostado  a2:')
a3=int(input('digite numero apostado  a3:')
a4=int(input('digite numero apostado  a4:')
a5=int(input('digite numero apostado  a5:')
a6=int(input('digite numero apostado  a6:')
a7=int(input('digite a7:')
a8=int(input('digite a8:')
a9=int(input('digite a9:')
a10=int(input('digite a10:')
a11=int(input('digite a11:')
a12=int(input('digite a12:')

if ('a1 conseguindo três valores')
    print('sena')
if('a1 conseguindo quatro valores')
    print('quadra')
if ('a1 conseguindo cinco valores')
    print('quina')
if ('a1 conseguindo seis valores')
    print('sena')
if ('a1 não conseguindo nenhum valor')
    print('AZAR')
if ('a2 conseguindo três valores')
    print('sena')
if ('a2 conseguindo quatro valores')
    print('quadra')
if ('a2 conseguindo cinco valores')
    print('quina')
if ('a2 conseguindo seis valores')
    print('sena')
if ('a2 não conseguindo nenhum valor')
    print('AZAR')
if ('a3 conseguindo três valores')
    print('sena')
if ('a3 conseguindo quatro valores')
    print('quadra')
if ('a3 conseguindo cinco valores')
    print('quina')
if ('a3 conseguindo seis valores')
    print('sena')
if ('a3 não conseguindo nenhum valor')
    print('AZAR')
if ('a4 conseguindo três valores')
    print('sena')
if ('a4 conseguindo quatro valores')
    print('quadra')
if ('a4 conseguindo cinco valores')
    print('quina')
if ('a4 conseguindo seis valores')
    print('sena')
if ('a4 não conseguindo nenhum valor')
    print('AZAR')
if ('a5 conseguindo três valores')
    print('sena')
if ('a5 conseguindo quatro valores')
    print('quadra')
if ('a5 conseguindo cinco valores')
    print('quina')
if ('a5 conseguindo seis valores')
    print('sena')
if ('a5 não conseguindo nenhum valor')
    print('AZAR')
if ('a6 conseguindo três valores')
    print('sena')
if ('a6 conseguindo quatro valores')
    print('quadra')
if ('a6 conseguindo cinco valores')
    print('quina')
if ('a6 conseguindo seis valores')
    print('sena')
if ('a6 não conseguindo nenhum valor')
    print('AZAR')
